"""initial schema

Revision ID: 19b0096d7587
Revises: 
Create Date: 2026-03-26 17:55:38.624354

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '19b0096d7587'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consumer_lag_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('consumer_group', sa.Text(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=False),
    sa.Column('partition', sa.SmallInteger(), nullable=False),
    sa.Column('lag_messages', sa.BigInteger(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_consumer_lag_time', 'consumer_lag_log', ['recorded_at'], unique=False)
    op.create_index('idx_consumer_lag_topic', 'consumer_lag_log', ['topic', 'partition'], unique=False)
    op.create_index(op.f('ix_consumer_lag_log_recorded_at'), 'consumer_lag_log', ['recorded_at'], unique=False)
    op.create_table('geopolitical_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tag', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_geopolitical_events_tag'), 'geopolitical_events', ['tag'], unique=True)
    op.create_table('price_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('commodity', sa.Text(), nullable=False),
    sa.Column('price_usd', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('price_local', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('local_currency', sa.String(length=3), nullable=True),
    sa.Column('fx_rate_to_usd', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('unit_raw', sa.Text(), nullable=True),
    sa.Column('unit_normalized', sa.Text(), nullable=True),
    sa.Column('unit_conversion_factor', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('source_priority', sa.SmallInteger(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('season', sa.Text(), nullable=True),
    sa.Column('day_of_year', sa.SmallInteger(), nullable=True),
    sa.Column('day_of_year_sin', sa.Float(), nullable=True),
    sa.Column('day_of_year_cos', sa.Float(), nullable=True),
    sa.Column('data_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('latency_minutes', sa.Integer(), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_price_events_commodity_time', 'price_events', ['commodity', 'data_as_of'], unique=False)
    op.create_index('idx_price_events_stale', 'price_events', ['is_stale'], unique=False, postgresql_where=sa.text('is_stale'))
    op.create_index(op.f('ix_price_events_commodity'), 'price_events', ['commodity'], unique=False)
    op.create_index(op.f('ix_price_events_data_as_of'), 'price_events', ['data_as_of'], unique=False)
    op.create_index(op.f('ix_price_events_ingested_at'), 'price_events', ['ingested_at'], unique=False)
    op.create_index(op.f('ix_price_events_is_stale'), 'price_events', ['is_stale'], unique=False)
    op.create_index(op.f('ix_price_events_region'), 'price_events', ['region'], unique=False)
    op.create_table('feature_vectors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('price_event_id', sa.BigInteger(), nullable=True),
    sa.Column('commodity', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('rolling_7d_avg', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('rolling_30d_std', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('momentum', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('energy_lag_corr', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('fertilizer_index_delta', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('seasonal_index', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('seasonal_adjusted_price', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('is_seasonal_adjusted', sa.Boolean(), nullable=True),
    sa.Column('is_low_confidence', sa.Boolean(), nullable=True),
    sa.Column('raw_price_usd', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('day_of_year_sin', sa.Float(), nullable=True),
    sa.Column('day_of_year_cos', sa.Float(), nullable=True),
    sa.Column('data_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['price_event_id'], ['price_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feature_vectors_commodity_time', 'feature_vectors', ['commodity', 'computed_at'], unique=False)
    op.create_index(op.f('ix_feature_vectors_commodity'), 'feature_vectors', ['commodity'], unique=False)
    op.create_index(op.f('ix_feature_vectors_computed_at'), 'feature_vectors', ['computed_at'], unique=False)
    op.create_table('anomaly_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('feature_id', sa.BigInteger(), nullable=True),
    sa.Column('commodity', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('anomaly_score', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('severity', sa.Text(), nullable=True),
    sa.Column('model_version', sa.Text(), nullable=True),
    sa.Column('is_anomaly', sa.Boolean(), nullable=True),
    sa.Column('alerted', sa.Boolean(), nullable=True),
    sa.Column('suppressed', sa.Boolean(), nullable=True),
    sa.Column('alert_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['feature_id'], ['feature_vectors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_anomaly_log_commodity', 'anomaly_log', ['commodity', 'detected_at'], unique=False)
    op.create_index('idx_anomaly_log_detected', 'anomaly_log', ['detected_at'], unique=False)
    op.create_index(op.f('ix_anomaly_log_commodity'), 'anomaly_log', ['commodity'], unique=False)
    op.create_index(op.f('ix_anomaly_log_detected_at'), 'anomaly_log', ['detected_at'], unique=False)
    op.create_table('anomaly_geo_tags',
    sa.Column('anomaly_id', sa.BigInteger(), nullable=False),
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['anomaly_id'], ['anomaly_log.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['geopolitical_events.id'], ),
    sa.PrimaryKeyConstraint('anomaly_id', 'event_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('anomaly_geo_tags')
    op.drop_index(op.f('ix_anomaly_log_detected_at'), table_name='anomaly_log')
    op.drop_index(op.f('ix_anomaly_log_commodity'), table_name='anomaly_log')
    op.drop_index('idx_anomaly_log_detected', table_name='anomaly_log')
    op.drop_index('idx_anomaly_log_commodity', table_name='anomaly_log')
    op.drop_table('anomaly_log')
    op.drop_index(op.f('ix_feature_vectors_computed_at'), table_name='feature_vectors')
    op.drop_index(op.f('ix_feature_vectors_commodity'), table_name='feature_vectors')
    op.drop_index('idx_feature_vectors_commodity_time', table_name='feature_vectors')
    op.drop_table('feature_vectors')
    op.drop_index(op.f('ix_price_events_region'), table_name='price_events')
    op.drop_index(op.f('ix_price_events_is_stale'), table_name='price_events')
    op.drop_index(op.f('ix_price_events_ingested_at'), table_name='price_events')
    op.drop_index(op.f('ix_price_events_data_as_of'), table_name='price_events')
    op.drop_index(op.f('ix_price_events_commodity'), table_name='price_events')
    op.drop_index('idx_price_events_stale', table_name='price_events', postgresql_where=sa.text('is_stale'))
    op.drop_index('idx_price_events_commodity_time', table_name='price_events')
    op.drop_table('price_events')
    op.drop_index(op.f('ix_geopolitical_events_tag'), table_name='geopolitical_events')
    op.drop_table('geopolitical_events')
    op.drop_index(op.f('ix_consumer_lag_log_recorded_at'), table_name='consumer_lag_log')
    op.drop_index('idx_consumer_lag_topic', table_name='consumer_lag_log')
    op.drop_index('idx_consumer_lag_time', table_name='consumer_lag_log')
    op.drop_table('consumer_lag_log')
    # ### end Alembic commands ###
