apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sentinel-models-pvc
  namespace: food-price-sentinel
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard
